### PR TITLE
chore: make linter and clippy happy

### PR DESCRIPTION
**Pull request by matthiasgoergens**
Via repeated application of
```bash
cargo fix --allow-dirty
cargo clippy --allow-dirty --fix --all -- -D warnings -D clippy::pedantic
cargo fmt
```
until we reach a fixed point.

### CODE REVIEW

**Comment by matthiasgoergens** [comment]
I suggest reviewing this via re-running the same commands against `dev` and checking if you get the same result.  (Just to check that there's no funny business going on.)

**Review by jtguibas — APPROVED** [review]

**Review by jtguibas — APPROVED** [review]

**Comment by jtguibas** [comment]
It seems like CI fails for some reason. I will investigate.

**Comment by matthiasgoergens** [comment]
Looks like your clippy version has more suggestions.

**Comment by jtguibas** [comment]
Closing this for now as the branch has gotten a bit out of sync.

**Pull request closed without merging**
