### PR TITLE
feat: weierstrass decompress precompile

### PR DESCRIPTION
**Pull request by brozorec**
After the successful merge of https://github.com/succinctlabs/sp1/pull/417 we can already use curves with fields bigger than 32 bytes (before that PR the 32 bytes requirement was hard-coded). BLS12-381 is a pairing-friendly elliptic curve used in Ethereum 2.0 whose field is 48 bytes. 

This PR adds:
1. the new BLS12-381 curve and its parameters
2. a precompile for a point decompression that internally uses the [snowbridge-amcl](https://crates.io/crates/snowbridge-amcl) crate

Notes:
I'm experimenting by running helios in SP1 and trying to prove the validity of the sync committee's aggregated signature in Ethereum block headers. The 1st step of this process is to decompress all 512 pubkeys of the sync committee. Without a precompile it consumes 2.9M cycles per key (or ~1.5B for all). It now takes only 33M for all the decompression, that's a 45x gain.

### CODE REVIEW

**Comment by brozorec** [comment]
That's definitely possible. There's only one potential issue I see for the moment. In the generics for add and double, there's a dangling `SyscallCode::SECP256K1_ADD.syscall_id()` https://github.com/succinctlabs/sp1/blob/f0154158bab6e86dfa7520fbe2565c5a60897609/core/src/syscall/precompiles/weierstrass/weierstrass_add.rs#L321

I see a possibility to pass the syscall id in the initializer [here](https://github.com/succinctlabs/sp1/blob/f0154158bab6e86dfa7520fbe2565c5a60897609/core/src/stark/air.rs#L121) and [here](https://github.com/succinctlabs/sp1/blob/f0154158bab6e86dfa7520fbe2565c5a60897609/core/src/runtime/syscall.rs#L232) and store it as a new struct field. Wdyt?

**Comment by brozorec** [comment]
As per the suggestions above, this PR adds a precompile for bls12-381 decompression but in a more generic way: by using a newly created `WeierstrassDecompressChip` similar to sw add and double. K256 decompress precompile is now implemented with the new chip under the hood and the custom code for it was removed.
@puma314

**Comment by storojs72** [comment]
hi, @brozorec!

Thank you for your work!

Did you try to run `cargo prove prove` for `bus-decompress` external test program?

I'm currently getting following issue:

```
artemstorozhuk@192 bls-decompress % cargo prove prove
   . . .
2024-04-11T11:02:33.034695Z  INFO coset_lde_batch: close time.busy=4.99ms time.idle=2.83µs dims=11x65536
2024-04-11T11:02:33.036944Z  INFO coset_lde_batch: close time.busy=2.22ms time.idle=999ns dims=37x16384
2024-04-11T11:02:33.071360Z  INFO loading memory image
2024-04-11T11:02:33.071867Z  INFO starting execution
2024-04-11T11:02:33.071873Z  INFO clk = 0 pc = 0x2015cc    
thread 'main' panicked at core/src/syscall/hint.rs:18:13:
not enough vecs in hint input stream
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
artemstorozhuk@192 bls-decompress % 
``` 

At the same time, I can confirm that `test_weierstrass_bls_decompress` works with following output

```
   . . .
2024-04-11T10:37:52.643861Z  INFO summary: cycles=118947, e2e=2474, khz=48.08, proofSize=2.11 MiB
test syscall::precompiles::weierstrass::weierstrass_decompress::tests::test_weierstrass_bls_decompress ... ok
```

**Comment by brozorec** [comment]
Hey @storojs72 no, I didn't but after running it, I got something different than yours:
```
    Finished release [optimized] target(s) in 0.08s
2024-04-12T08:50:28.597363Z  INFO runtime.run(...):load memory: close time.busy=941µs time.idle=981ns
thread 'main' panicked at core/src/runtime/syscall.rs:84:18:
invalid syscall number: 240
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-04-12T08:50:28.597513Z  INFO runtime.run(...): close time.busy=1.10ms time.idle=2.11µs
```

I ran `cargo prove prove` in "tests/ed-decompress" and "tests/secp256k1-decompress" on succinct's repo main branch and I'm getting a similar output.

**Comment by storojs72** [comment]
I guess you've installed `cargo prove` as it is [recommended](https://succinctlabs.github.io/sp1/getting-started/install.html#option-1-prebuilt-binaries-recommended) in documentation, using prebuilt binaries. Probably you need to re-install `cargo prove` tool from your specific sp1 codebase. See [README](https://github.com/succinctlabs/sp1/tree/main/cli) for more details.

**Comment by brozorec** [comment]
> I was getting similar issues - invalid syscall codes for every test program. I guess you've installed `cargo prove` as it is [recommended](https://succinctlabs.github.io/sp1/getting-started/install.html#option-1-prebuilt-binaries-recommended) in documentation, using prebuilt binaries. Probably you need to re-install `cargo prove` tool from your specific sp1 codebase. See [README](https://github.com/succinctlabs/sp1/tree/main/cli) for more details.

I re-installed it and now it's up to date. However, when I ran `cargo prove prove` in "test/secp256k1-decompress" on succinct/main, I'm still getting:
```
    Finished release [optimized] target(s) in 0.14s
2024-04-12T11:18:55.690068Z  INFO coset_lde_batch: close time.busy=23.6ms time.idle=4.30µs dims=11x65536
2024-04-12T11:18:55.704910Z  INFO coset_lde_batch: close time.busy=14.8ms time.idle=3.47µs dims=37x16384
2024-04-12T11:18:56.105531Z  INFO loading memory image
2024-04-12T11:18:56.106522Z  INFO starting execution
2024-04-12T11:18:56.106557Z  INFO clk = 0 pc = 0x201600    
240
thread 'main' panicked at core/src/syscall/hint.rs:18:13:
not enough vecs in hint input stream
```
This PR's bls-decompress is heavily based on the main's secp256k1-decompress, so it's probably no surprise that this is showing off in bls-decompress as well. Do you have an idea what the cause could be?

**Comment by storojs72** [comment]
For this, I think the reason is that `cargo prove prove` doesn't support provision stdin. So it runs your external program without it and when program doesn't receive vector of bytes with encoded point from stdin it panics. That is why if you run program from your unit-test (where program is instantiated from ELF file), where stdin is provided it works but doesn't work with `cargo prove prove`. I noticed that by changing stdin expecting to hardcoded value and then `cargo prove prove` worked

**Review by jtguibas — APPROVED** [review]

**Pull request merged**
